apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::911078995732:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SFCFKYJGOM3S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::911078995732:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-26T12:27:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1481"
  uid: 9a4d2f47-a1e0-45f1-bd3b-df9abe188373
