apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::584452332558:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-135MM0HK10PCD
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-25T16:44:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1769"
  uid: 85bce784-73b8-4b7f-a259-8bd434a2456b
